# Generated by Django 4.2.2 on 2023-06-20 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='distributorId',
        ),
        migrations.AddField(
            model_name='requests',
            name='distributor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributor.distributor'),
        ),
    ]
